(()=>{"use strict";
const base=[
['ghivil','Ghivil',['ES'],7,3,2,1.5,1.5],['calin','Călin',['IS'],7,3,2,2,1.5],['bizau','Bizău',['C'],7,3,2,1.5,2],['coman','Coman',['ID'],7,3,2,1.5,2],['paul','Paul',['ED'],7,3,2,1.5,2],['ali','Ali',['P'],3,5,3,1,3],['iliescu','Iliescu',['ES'],7,3,2,1.5,2],['ciripoiu','Ciripoiu',['IS','ID'],7,3,2,1.8,2],['vujic','Vujic',['C'],7,3,2,1.4,2],['burzo','Burzo',['ID'],7,3,2,1.4,2],['ostace','Ostace',['ID'],7,3,2,1.4,2],['tomas','Tomas',['ED'],7,3,2,1.5,2],['bobo','Bobo',['ED'],7,3,2,1.5,2],['duta','Duta',['P'],7,3,2,1.3,2],['costea','Costea',['P'],7,3,2,1.3,2],['merla','Merla',['GK'],12,8,5,1,2],['tenghea','Tenghea',['GK'],12,8,5,1,2]];
const fresh=()=>({running:false,phase:'attack',match:0,last:Date.now(),history:[],attack:{ES:'ghivil',IS:'calin',C:'bizau',ID:'coman',ED:'paul',P:'ali',GK:'merla'},defence:{ES:'ghivil',IS:'ciripoiu',C:'bizau',ID:'coman',ED:'paul',P:'ali',GK:'merla'},players:Object.fromEntries(base.map(x=>[x[0],{id:x[0],name:x[1],posts:x[2],fatigue:{green:x[3],yellow:x[4],red:x[5]},recovery:x[6],minRest:x[7],load:0,total:0,attackTime:0,defenceTime:0,benchTime:0,suspension:0,manual:null}])),pos:{attack:{ES:[15,24],IS:[29,20],C:[43,17],P:[50,34],ID:[71,20],ED:[85,24],GK:[50,7]},defence:{ES:[16,75],IS:[30,80],C:[42,84],P:[50,70],ID:[70,80],ED:[84,75],GK:[50,94]}}});
let state;try{state=JSON.parse(localStorage.getItem('hbrb-v1'))||fresh()}catch(e){state=fresh()}
const $=s=>document.querySelector(s),fmt=s=>{s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},p=id=>state.players[id],ids=ph=>Object.values(state[ph]),save=()=>{try{localStorage.setItem('hbrb-v1',JSON.stringify(state))}catch(e){}};
const snap=()=>{state.history.push(JSON.parse(JSON.stringify({attack:state.attack,defence:state.defence,players:state.players,phase:state.phase,match:state.match})));if(state.history.length>30)state.history.shift()};
function level(x){if(x.manual)return x.manual;let g=x.fatigue.green*60,y=x.fatigue.yellow*60,r=x.fatigue.red*60;return x.load<g?'green':x.load<g+y?'yellow':x.load<g+y+r?'red':'purple'}
function ready(x){let safe=(x.fatigue.green+x.fatigue.yellow)*60-60,ex=Math.max(0,x.load-safe),a=ex/Math.max(.1,x.recovery),b=Math.max(0,x.minRest*60-x.benchTime),s=Math.max(a,b);return{ok:s<1,s}}
function token(id,pos,ph){let x=p(id),l=level(x);return `<button class="token ${l}${x.suspension>0?' suspended':''}" data-id="${id}" style="left:${state.pos[ph][pos][0]}%;top:${state.pos[ph][pos][1]}%"><span class="n">${x.name}</span><span class="t">${fmt(x.total)}</span><span class="p">${pos}${x.suspension>0?' · '+fmt(x.suspension):''}</span></button>`}
function render(){ $('#clock').textContent=fmt(state.match);$('#attackMode').classList.toggle('active',state.phase==='attack');$('#defenceMode').classList.toggle('active',state.phase==='defence');
$('#attackLayer').innerHTML=Object.entries(state.attack).map(([k,v])=>token(v,k,'attack')).join('');$('#defenceLayer').innerHTML=Object.entries(state.defence).map(([k,v])=>token(v,k,'defence')).join('');
document.querySelectorAll('.token').forEach(e=>e.onclick=()=>open(e.dataset.id));
let active=new Set(ids(state.phase));let list=Object.values(state.players).filter(x=>!active.has(x.id)).sort((a,b)=>a.posts[0].localeCompare(b.posts[0])||a.name.localeCompare(b.name));
$('#bench').innerHTML=list.map(x=>{let r=ready(x),l=level(x);return `<div class="benchCard" data-id="${x.id}"><div class="dot ${l}"></div><div><div class="name">${x.name}</div><div class="meta">${x.posts.join('/')} · total ${fmt(x.total)} · load ${fmt(x.load)}</div></div><div class="ready ${r.ok?'ok':'wait'}">${x.suspension>0?'2’ '+fmt(x.suspension):r.ok?'READY':fmt(r.s)}</div></div>`}).join('');
document.querySelectorAll('.benchCard').forEach(e=>e.onclick=()=>open(e.dataset.id));}
function open(id){let x=p(id),ap=Object.entries(state.attack).find(([,v])=>v===id)?.[0]||'-',dp=Object.entries(state.defence).find(([,v])=>v===id)?.[0]||'-';
$('#modal').innerHTML=`<h2>${x.name}</h2><div class="stats"><div class="stat"><small>TOTAL</small><b>${fmt(x.total)}</b></div><div class="stat"><small>LOAD</small><b>${fmt(x.load)}</b></div><div class="stat"><small>ATAC</small><b>${fmt(x.attackTime)}</b></div><div class="stat"><small>APĂRARE</small><b>${fmt(x.defenceTime)}</b></div></div>
<div class="actions"><button id="subBtn">SCHIMBĂ</button><button id="two" class="danger">ELIMINARE 2’</button><button id="clear2">ANULEAZĂ 2’</button></div>
<h3>Stare fizică</h3><div class="fatigue"><button data-f="green" class="green">VERDE</button><button data-f="yellow" class="yellow">GALBEN</button><button data-f="red" class="red">ROȘU</button><button data-f="purple" class="purple">MOV</button><button id="auto">AUTO</button></div>
<h3>Profil</h3><div class="fieldGrid"><label class="field">Verde<input id="g" type="number" step=".5" value="${x.fatigue.green}"></label><label class="field">Galben<input id="y" type="number" step=".5" value="${x.fatigue.yellow}"></label><label class="field">Roșu<input id="r" type="number" step=".5" value="${x.fatigue.red}"></label><label class="field">Recovery ×<input id="rec" type="number" step=".1" value="${x.recovery}"></label><label class="field">Pauză minimă<input id="rest" type="number" step=".5" value="${x.minRest}"></label></div><div class="actions"><button id="saveProfile">SALVEAZĂ</button></div><div class="meta">Atac: ${ap} · Apărare: ${dp}</div><div id="subs"></div>`;
$('#backdrop').classList.remove('hidden');$('#two').onclick=()=>{snap();x.suspension=120;save();open(id)};$('#clear2').onclick=()=>{snap();x.suspension=0;save();open(id)};
document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{snap();x.manual=b.dataset.f;save();open(id)});$('#auto').onclick=()=>{snap();x.manual=null;save();open(id)};
$('#saveProfile').onclick=()=>{snap();x.fatigue.green=+$('#g').value||0;x.fatigue.yellow=+$('#y').value||0;x.fatigue.red=+$('#r').value||0;x.recovery=Math.max(.1,+$('#rec').value||1);x.minRest=Math.max(0,+$('#rest').value||0);save();open(id)};
$('#subBtn').onclick=()=>showSubs(id)}
function showSubs(out){let phases=['attack','defence'].filter(ph=>ids(ph).includes(out)),c=Object.values(state.players).filter(x=>x.id!==out&&x.suspension<=0);$('#subs').innerHTML='<h3>Înlocuitor</h3>'+c.map(x=>{let rr=ready(x);return `<div class="sub" data-sub="${x.id}"><b>${x.name} · ${x.posts.join('/')}</b><span>${rr.ok?'READY':fmt(rr.s)}</span></div>`}).join('');document.querySelectorAll('[data-sub]').forEach(e=>e.onclick=()=>{snap();phases.forEach(ph=>{let z=Object.entries(state[ph]).find(([,v])=>v===out);if(z)state[ph][z[0]]=e.dataset.sub});save();$('#backdrop').classList.add('hidden');render()})}
function tick(){let now=Date.now(),dt=Math.min(2,(now-state.last)/1000);state.last=now;if(state.running){state.match+=dt;let a=new Set(ids(state.phase));Object.values(state.players).forEach(x=>{if(x.suspension>0)x.suspension=Math.max(0,x.suspension-dt);if(a.has(x.id)&&x.suspension<=0){x.total+=dt;x.load+=dt;x.benchTime=0;state.phase==='attack'?x.attackTime+=dt:x.defenceTime+=dt}else{x.benchTime+=dt;x.load=Math.max(0,x.load-dt*x.recovery)}})}render();save();requestAnimationFrame(tick)}
$('#start').onclick=()=>{state.running=true;state.last=Date.now()};$('#pause').onclick=()=>state.running=false;$('#attackMode').onclick=()=>state.phase='attack';$('#defenceMode').onclick=()=>state.phase='defence';$('#undo').onclick=()=>{let h=state.history.pop();if(h){state.attack=h.attack;state.defence=h.defence;state.players=h.players;state.phase=h.phase;state.match=h.match;save();render()}};$('#reset').onclick=()=>{if(confirm('Resetezi meciul?')){state=fresh();save();render()}};$('#close').onclick=()=>$('#backdrop').classList.add('hidden');$('#backdrop').onclick=e=>{if(e.target.id==='backdrop')$('#backdrop').classList.add('hidden')};render();requestAnimationFrame(tick);
})();